controllers:
    resource: ../src/Controller/
    type: attribute
app_user_edit_status:
    path: '/user/{id}/edit-status'
    # controller: 'App\Controller\VotreController::editStatus'
    controller: 'App\Controller\UserController::editStatus'
    methods: ['POST']